'use strict'

export const CHANGE_SELECTED_CATEGORY = 'CHANGE_SELECTED_CATEGORY'
export const SAVE_CATEGORY = 'SAVE_CATEGORY'
export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const CHANGE_MODAL_VALUE = 'CHANGE_MODAL_VALUE'

export const TOGGLE_IS_SHOW_COMPLETED_TODOS = 'TOGGLE_IS_SHOW_COMPLETED_TODOS'
export const CHANGE_SELECTED_TODO = 'CHANGE_SELECTED_TODO'
export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS'
export const SAVE_TODO = 'SAVE_TODO'
export const DELETE_TODO = 'DELETE_TODO'

export const CHANGE_SORT_VALUE = 'CHANGE_SORT_VALUE'
